[package]
name = "gy-271"
version = "0.1.0"
authors = ["Erik Schroeder <schroedererik@mailbox.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2"
nalgebra = "0.24"
